const reels = [
  {
    username: "travel_with_arya",
    likeCount: 12400,
    isLiked: false,
    commentCount: 340,
    caption: "Exploring the mountains 🏔️✨",
    video: "",
    userprofile: "arya.jpg",
    shareCount: 120,
    isFollowed: true,
  },
  {
    username: "foodie_mania",
    likeCount: 8600,
    isLiked: true,
    commentCount: 190,
    caption: "Crispy momos + spicy chutney 🔥",
    video: "",
    userprofile: "foodie.jpg",
    shareCount: 90,
    isFollowed: false,
  },
  {
    username: "dance_with_riya",
    likeCount: 9800,
    isLiked: true,
    commentCount: 260,
    caption: "Weekend vibe dance 💃✨",
    video: "",
    userprofile: "riya.jpg",
    shareCount: 150,
    isFollowed: false,
  },
  {
    username: "nature_snap",
    likeCount: 17900,
    isLiked: true,
    commentCount: 510,
    caption: "Sunset hits different 🌅✨",
    video: "",
    userprofile: "nature.jpg",
    shareCount: 300,
    isFollowed: true,
  },
  {
    username: "car_world",
    likeCount: 19800,
    isLiked: false,
    commentCount: 490,
    caption: "This engine sound 😍🔥",
    video: "",
    userprofile: "car.jpg",
    shareCount: 350,
    isFollowed: false,
  },
];
